## Quick Introduction to Python and OpenCV

We will cover basic data types, data structures, loops, functions in Python. We will also make an intro to Numpy, which is a very powerful library for Python.

After Python intro, we will make a short start to OpenCV.

Some of the content is taken from: https://colab.research.google.com/github/cs231n/cs231n.github.io/blob/master/python-colab.ipynb#scrollTo=sk_8DFcuL9ey


# Data Types

## Numbers

In [1]:
x = 15  # Assignment
print(x + 5)  # Addition
print(x - 5)  # Subtraction
print(x * 3 + 5)  # Multiplication
print(x ** 2 + 5) # Exponentiation

20
10
50
230


In [2]:
print(type(x))
y = x + 0.9
print(type(y))

<class 'int'>
<class 'float'>


In [3]:
print(x/4)  # Division
print(x//4) # Quotient
print(x%4)  # Remainder (or modulo)

3.75
3
3


## Booleans

In [4]:
a, b = True, False
print(a and b)  
print(a or b)
print(not a)
print((not a) and (not b))

False
True
False
False


## Strings

In [5]:
name_1 = "John"
name_2 = 'Michael'
print(name_1 + ", " + name_2)
print(name_1[1])  # You can treat them as an array of characters

John, Michael
o


# Data Structures

Common data structures are lists, dictionaries, tuples, sets.

## Lists

In [6]:
arr = [3, "asd", 4]
print("Size of list is " + str(len(arr)))

Size of list is 3


In [7]:
print(arr[0])   # List indexing
print(arr[0:]) # Slicing - indexing a range of values (start:end:stepsize)
print(arr[::2]) # If start and end aren't provided, considers the entire list
print(arr[-1])  # You can also index using negative values in the reverse order
print(arr[:-1]) # Start = 0, End = -1

3
[3, 'asd', 4]
[3, 4]
4
[3, 'asd']


In [8]:
arr.append("new") # Add new item to a list
arr.remove("asd") # Delete by value (Be mindful about duplicates)
print(arr)
del arr[-1]  # Delete by index
print(arr)

[3, 4, 'new']
[3, 4]


In [9]:
arr.append(4)
print(arr)
print(arr.index(4)) # Returns the index of value (first occurence)
val_to_remove = arr[arr.index(4)]
arr.remove(val_to_remove)
print(arr)

[3, 4, 4]
1
[3, 4]


In [10]:
arr_2 = [5, 6, 7]
print(arr + arr_2)  # Concatenate two lists
print(arr[:1] + arr_2 + arr[1:])  # Combining arrays in different ways


[3, 4, 5, 6, 7]
[3, 5, 6, 7, 4]


How to loop through lists to transform data?

In [11]:
arr = arr + arr_2
for x in arr:
  print(x**2)

9
16
25
36
49


In [12]:
# If you want to keep track of index, use enumerate()

for counter, x in enumerate(arr):
  if(counter == 2):
    print(counter, x)
  else:
    print(counter, x**2)

0 9
1 16
2 5
3 36
4 49


In [13]:
squares = [x**2 for x in arr]  # Possible to loop in a single line
print(squares)
large_squares = [x**2 for x in arr if x>=5] # It is possible to add conditions
print(large_squares)

[9, 16, 25, 36, 49]
[25, 36, 49]


## Dictionaries

Dictionaries consist of key-value pairs. 

In [14]:
dict_modules = {"GV1":"Computer Vision", "GV2": "Machine Learning", "GV3": "Computer Graphics"}
print(dict_modules.keys())
print(dict_modules.values())


dict_keys(['GV1', 'GV2', 'GV3'])
dict_values(['Computer Vision', 'Machine Learning', 'Computer Graphics'])


In [15]:
print(dict_modules["GV1"])
print("GV4" in dict_modules)
dict_modules["GV4"] = "Augmented Reality" # Create new entry
dict_modules["GV1"] = "CV" # Modify an entry
print("GV4" in dict_modules)

Computer Vision
False
True


In [16]:
dict_modules['GV1'] = {"Module":"Computer Vision", "Credits":5, "Midterms": None}
dict_modules['GV1']['Credits']

5

In [17]:
for key, value in dict_modules.items():
  print(key, value)

GV1 {'Module': 'Computer Vision', 'Credits': 5, 'Midterms': None}
GV2 Machine Learning
GV3 Computer Graphics
GV4 Augmented Reality


## Tuples

In [18]:
tple = (1,5)
tple_list = []
for i in range(5):
  new_tple = (tple[0]+i,tple[1]+i)    # Access tuple elements by index
  tple_list.append( new_tple )
  print(new_tple)

(1, 5)
(2, 6)
(3, 7)
(4, 8)
(5, 9)


## Sets

In [19]:
days = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"}

for day in days:
  print(day)

Monday
Friday
Sunday
Saturday
Tuesday
Thursday
Wednesday


# Functions and Classes

In [20]:
def function(a, b):
  if(a > b):
    return True
  else:
    return False

print(function(5,3))
print(function(3,5))

True
False


In [21]:
class City:

  def __init__(self, name, isCapital):
    self.name = name
    self.isCapital = isCapital

  def SetPopulation(self, population):
    self.population = population
  
  def DisplayInfo(self):
    capital_word = "" if self.isCapital == True else "not "
    print("City of " + self.name + " has a population of " + str(self.population/10**6) + "M and it is " + capital_word + "a capital.")

city1 = City("Dublin", True)
city1.SetPopulation(1300000)
city1.DisplayInfo()

City of Dublin has a population of 1.3M and it is a capital.


# NumPy

A great library to store, transform, manipulate large multidimensional arrays.

In [22]:
import numpy as np

In [23]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr)
print(arr.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [24]:
# Other ways to create arrays
zeros = np.zeros((5,5))
print(zeros)

ones = np.ones((3,3))
print(ones)

random = np.random.random((3,2))
print(random)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.4522757  0.89569084]
 [0.23683468 0.55282505]
 [0.98220068 0.56630439]]


In [25]:
print(arr[0,0])  # First dimension for row, second dimension for column
print(arr[1,1])
print(arr[0,-1])  # We can use negative indexing again

1
5
3


In [26]:
print(arr[0,:]) # Slicing
print(arr[:,-1])

[1 2 3]
[3 6]


In [27]:
arr_2 = arr+arr # Unlike lists, you can add numpy arrays easily
print(arr_2)

[[ 2  4  6]
 [ 8 10 12]]


In [28]:
print(arr_2**2)
print(arr_2/4)

[[  4  16  36]
 [ 64 100 144]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


# An Introductory Image Processing Example

We now make an introduction to OpenCV. Detailed tutorials can be found on https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html

This example covers multiple steps:
 - Load an image dataset
 - Display the image
 - Some basic operations on the image using OpenCV

In [29]:
from sklearn.datasets import load_sample_images
import cv2 as cv  # Imports OpenCV
import numpy as np
# from google.colab.patches import cv2_imshow

dataset = load_sample_images()     

In [30]:
print(dataset.keys())
images = dataset['images']
print(type(images))

dict_keys(['images', 'filenames', 'DESCR'])
<class 'list'>


In [31]:
images[0].shape


(427, 640, 3)

# What do the different dimensions of this image represent?

Typically, digital images consist of RGB channels - Red, Green, Blue. Each channel consists of 8 bits, so they take values between 0-255.

Some devices can also capture depth as the 4th dimension - RGBD. They use Time-of-Flight, which is a technique to emit and receive a light source to calculate depth.

In [35]:

img = np.flip(images[1], axis=-1)   # Note that OpenCV needs images to be in B-G-R order. Normally, they're in R-G-B order. This

cv.imshow('222', img)

In [ ]:
b, g, r = cv.split(img) # Split the image into separate channels.
print(r.shape)

gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)  # Grayscale image
cv2_imshow(gray)

In [ ]:
img_green = cv.merge((np.zeros_like(g), g , np.zeros_like(g))) # Only uses Green channel
gray = cv.cvtColor(img_green, cv.COLOR_BGR2GRAY)  # Grayscale image
cv2_imshow(gray)

In [ ]:
img_2 = cv.merge((r,b,g))
cv2_imshow(img_2)

img_3 = cv.merge((b,r,g))
cv2_imshow(img_3)

In [ ]:
img_3[:,:,0] = 0  # Make all blues zero.
cv2_imshow(img_3)
print(img_3[:,:,0])

In [ ]:
center = img_3.shape[0]//2, img_3.shape[1]//2
crop_size = 150
img_cropped = img_3[center[0] - crop_size:center[0] + crop_size, center[1] - crop_size : center[1] + crop_size, :]
cv2_imshow(img_cropped)

In [ ]:
scale_percent = 50 # percent of original size
width = int(img_cropped.shape[1] * scale_percent / 100)   # Calculate new width
height = int(img_cropped.shape[0] * scale_percent / 100)  # Calculate new height
dim = (width, height)
  
# resize image
img_resized = cv.resize(img_cropped, dim, interpolation = cv.INTER_AREA)
cv2_imshow(img_resized)

In [ ]:
img_3[:150,:150,:] = img_resized  # Adds a resized flower
img_3[-150:,-150:,:] = img_resized
cv2_imshow(img_3)